# Configuração de conexões de workers
events {
    worker_connections 1024;
}

http {
    # Definindo o servidor de backend (Upstream)
    upstream backend {
        server backend:8000;
    }

    # Configuração do servidor HTTP
    server {
        listen 80;
        server_name localhost;

        # Redirecionamento das requisições de API para o container backend
        location /api/ {
            proxy_pass http://backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Servir arquivos estáticos do frontend ou rotas SPA (Single Page Application)
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}
